// mapping of brands to their common models for dropdowns
export const initialModels: Record<string, string[]> = {
    "ASTON MARTIN": ["DB9", "DBS", "RAPIDE", "VANTAGE V8", "VIRAGE", "DBX"],
    "AUDI": ["A4", "A6", "A8", "Q5", "Q7", "R8", "RS 5", "Q3", "RS6", "RS7", "S5", "Q8", "RS", "Q2", "E TRON SPORTBACK", "A8L", "Q3 Sportback"],
    "BENTLEY": ["RANGE", "CONTINENTAL FLYING SPUR", "CONTINENTAL GT", "CONTINENTAL SUPERSPORTS", "MULSANNE", "TURBO R", "BENTAYGA", "FLYING SPUR", "CONTINENTAL"],
    "BMW": ["3 Series", "5 Series", "6 Series Convertible", "7 Series", "840 Cl", "M Models", "X1 Series", "X3 Series", "X5 Series", "Z3 Models", "Z4 Models", "X6 M", "GRAN TURISMO", "BMW 7 Series", "X1", "i8", "6 Series", "X4", "M8", "2 Series", "X5 M", "X7 Series", "i3", "M340i", "XM", "i7", "M2", "iX", "i4", "iX1"],
    "BYD": ["e6", "Atto 3", "Seal", "eMax", "Sealion"],
    "CHEVROLET": ["BEAT", "SPARK", "ENJOY"],
    "CITROEN": ["C5 Aircross", "C3", "eC3", "C3 Aircross", "Basalt", "Aircross"],
    "FERRARI": ["599", "F 149", "F 430", "458", "F 151", "488", "California"],
    "FORCE MOTORS": ["Gurkha", "Trax Cruiser"],
    "FORD": ["ENDEAVOUR", "ESCORT", "FIESTA", "FIGO", "IKON", "FIESTA 1.5", "ECOSPORT", "Figo Aspire", "FREESTYLE", "Aspire"],
    "HONDA": ["CITY", "CITY ZX", "NEW CITY", "AMAZE", "WR-V", "Elevate"],
    "HYUNDAI": ["ELANTRA", "i10 1.1", "i10 1.2 KAPPA", "i20", "TUCSON", "VERNA", "EON", "GRAND i10", "CRETA", "Venue", "Grand i10 Nios", "AURA", "Alcazar", "i20 N Line", "Venue N Line", "Ioniq 5", "EXTER", "Creta N Line", "Prime"],
    "ISUZU": ["D-Max", "MU X", "S-CAB"],
    "JAGUAR": ["XF", "XJ", "F-PACE"],
    "JEEP": ["Compass", "WRANGLER", "Meridian", "Grand Cherokee"],
    "KIA": ["SELTOS", "CARNIVAL", "Sonet", "Carens", "EV6", "EV9", "Syros", "Carens Clavis"],
    "LAMBORGHINI": ["GALLARDO", "MURCIELAGO LP 640", "AVENTADOR", "Huracan", "Urus"],
    "LAND ROVER": ["DEFENDER", "DISCOVERY 3", "FREELANDER 2", "RANGE ROVER", "RANGE ROVER SPORT", "RANGE ROVER SPORT HSC", "RANGE ROVER EVOQUE", "Discovery Sport", "VELAR"],
    "LEXUS": ["LX", "ES", "RX", "NX", "LM"],
    "MAHINDRA": ["BOLERO", "CLASSIC", "SCORPIO", "SCORPIO M HAWK", "THAR", "BOLERO POWER PLUS", "XUV300", "XUV700", "Scorpio N", "XUV 400", "XUV 3XO", "Thar Roxx", "XEV", "Be 6", "XUV 7XO", "XUV 3XO EV"],
    "MARUTI": ["800", "800 DUO", "A STAR", "ALTO", "ALTO K10", "BALENO", "EECO", "ESTEEM", "GRAND VITARA", "OMNI", "RITZ", "SWIFT", "SWIFT DZIRE", "WAGON R", "ZEN", "ERTIGA", "ESTILO 1.0 NEW", "ALTO 800", "STINGRAY", "SWIFT RANGE EXTENDER", "CELERIO", "CIAZ", "S CROSS", "VITARA BREZZA", "IGNIS", "DZIRE", "GYPSY", "CELERIO X", "XL6", "S-PRESSO", "BREEZA", "FRONX", "JIMNY", "INVC", "Model L"] ,
    "MERCEDES-BENZ": ["200 D", "240 D", "C CLASS", "E CLASS", "G CLASS", "GL CLASS", "MB 140", "ML CLASS", "S CLASS", "SLK CLASS", "B CLASS", "A CLASS", "E CLASS LIMOUSINE", "GLE CLASS", "GLA CLASS", "GLA", "CLA", "AMG GT", "GLC CLASS", "GLS CLASS", "AMG", "EQC", "EQS", "EQB", "Maybach GLS", "GLE", "Cale"],
    "MG": ["Hector", "Gloster", "Astor", "ZS EV", "Comet", "Windsor", "M9 EV", "Cyberster"],
    "MINI": ["MINI COOPER S", "MINI COOPER S COUNTRYMAN", "MINI COOPER", "MINI COOPER CONVERTIBLE", "MINI COOPER COUNTRYMAN", "Clubman"],
    "MITSUBISHI": ["LANCER", "PAJERO SPORT"],
    "NISSAN": ["MICRA", "TEANA", "X-TRAIL", "SUNNY", "EVALIA", "MICRA ACTIVE", "TERRANO", "MICRA NEW MC", "GTR", "Kicks", "Magnite", "Y62", "Gravite"],
    "PORSCHE": ["911", "BOXTER", "CAYENNE", "CAYENNE GTS", "CAYENNE TURBO", "PANAMERA", "PANAMERA TURBO", "MACAN", "Taycan"],
    "RENAULT": ["KOLEOS", "PULSE", "DUSTER", "SCALA", "LODGY", "Kwid", "CAPTUR", "Triber", "KIGER"],
    "ROLLS ROYCE": ["1938", "GHOST", "PHANTOM", "SILVER", "Cullinan"],
    "SKODA": ["LAURA", "OCTAVIA", "OCTAVIA COMBI", "SUPERB", "KODIAQ", "Karoq", "Kushaq", "SLAVIA", "Kylac"],
    "TATA": ["ARIA", "SAFARI", "SAFARI PETROL", "SIERRA", "SUMO", "SUMO VICTA", "VENTURE", "SUMO GOLD", "ZEST", "BOLT", "Movus", "TIAGO", "HEXA", "TIGOR", "NEXON", "Harrier", "ALTROZ", "SPACIO", "Punch", "ALTROZ DCA", "Nexon EV Max", "Nexon EV Prime", "TIAGO EV", "TIAGO NRG", "Curvv"],
    "TESLA": ["Model Y"],
    "TOYOTA": ["ALPHARD", "CAMRY", "COROLLA", "COROLLA ALTIS", "ETIOS", "FORTUNER", "INNOVA", "LAND CRUISER PRADO", "QUALIS", "ETIOS LIVA", "ETIOS Cross", "Innova Crysta", "LAND CRUISER", "GLANZA", "Urban Cruiser", "HILUX", "Vellfire", "Urban Cruiser Hyryder", "Innova Hycross", "Rumion", "Urban Cruiser Taisor"],
    "VINFAST": ["VF 7", "VF 6"],
    "VOLKSWAGEN": ["POLO", "POLO GT", "TIGUAN", "T-ROC", "Taigun", "Virtus", "Golf", "Tayron"],
    "VOLVO": ["S60", "XC 60", "XC 90", "S90", "XC 40", "EC40", "EC140", "EC40"]
};
