// Complete list of vehicle brands available in Indian market
export const initialBrands: string[] = [
    "ASTON MARTIN",
    "AUDI",
    "BENTLEY",
    "BMW",
    "BYD",
    "CHEVROLET",
    "CITROEN",
    "FERRARI",
    "FORCE MOTORS",
    "FORD",
    "HONDA",
    "HYUNDAI",
    "ISUZU",
    "JAGUAR",
    "JEEP",
    "KIA",
    "LAMBORGHINI",
    "LAND ROVER",
    "LEXUS",
    "MAHINDRA",
    "MARUTI",
    "MERCEDES-BENZ",
    "MG",
    "MINI",
    "MITSUBISHI",
    "NISSAN",
    "PORSCHE",
    "RENAULT",
    "ROLLS ROYCE",
    "SKODA",
    "TATA",
    "TESLA",
    "TOYOTA",
    "VINFAST",
    "VOLKSWAGEN",
    "VOLVO",
    // Commercial / specialty
    "ASHOK LEYLAND",
    "EICHER",
    "PIAGGIO",
    "SML ISUZU",
    "TATA COMMERCIAL",
];
